# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.TimeField(null=True),
        ),
    ]
